uchar judgebit(uchar num,uchar b);
void max(uchar *a,uchar *b);
uchar maxt(uchar a,uchar b,uchar c);
void clear(char le);
uchar abs(uchar a);
uchar abss(char a);
void trailler(uint speed);
void point(uchar x,uchar y,uchar z,uchar le);
 void type(uchar cha,uchar y);
void cirp(char cpp,uchar dir,uchar le);
void line(uchar x1,uchar y1,uchar z1,uchar x2,uchar y2,uchar z2,uchar le);
void box(uchar x1,uchar y1,uchar z1,uchar x2,uchar y2,uchar z2,uchar fill,uchar le);
void box_apeak_xy(uchar x1,uchar y1,uchar z1,uchar x2,uchar y2,uchar z2,uchar fill,uchar le);
void poke(uchar n,uchar x,uchar y);
void boxtola(char i,uchar n);
void rolldisplay(uint speed);
void roll_apeak_yz(uchar n,uint speed);
void roll_apeak_xy(uchar n,uint speed);
void roll_3_xy(uchar n,uint speed);
void trans(uchar z,uint speed);
void tranoutchar(uchar c,uint speed);
void transss();